baseURL: https://1pkg.github.io
title: Kostinatyn Masliuk | 1pkg dev blog
theme: papermod

enableRobotsTXT: false
buildDrafts: false
buildFuture: false
buildExpired: false

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  env: production
  title: Kostinatyn Masliuk | 1pkg dev blog
  description: Kostinatyn Masliuk | 1pkg dev blog
  author: Kostinatyn Masliuk

  ShowReadingTime: false
  ShowShareButtons: false
  comments: false
  defaultTheme: auto
  disableThemeToggle: false
  disableSpecial1stPost: false

  assets:
    favicon: favicon.ico
    favicon16x16: favicon-16x16.png
    favicon32x32: favicon-32x32.png

  label:
    text: '~'

  homeInfoParams:
    Title: /
    Content: >
      Hi there ğŸ‘‹ at 1pkg dev blog.
      My name is Kostinatyn Masliuk,
      I'm passionate software engineer and open source enthusiast.
      I'm mostly focused on distributed systems âš™ï¸, data intensive applications ğŸ—‚ï¸, cloud computing â˜ï¸ and Go,
      but also actively practicing in other forms of software development and trying to keep up with new software trends.

  socialIcons:
    - name: github
      url: 'https://github.com/1pkg'
    - name: linkedin
      url: 'https://www.linkedin.com/in/kostiantyn-masliuk-a0248617b/'
    - name: email
      url: 'mailto:1pkg@protonmail.com'
